version: "3.9"
services:
  api:
    build: .
    container_name: moura_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./app:/app/app
      - ./sql:/app/sql
    restart: unless-stopped

