version: 2

sources:
  - name: raw
    tables:
      - name: sales

models:
  - name: stg_sales
    description: "Camada silver: limpeza e tipagem de sales"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: total
        tests: [not_null]

  - name: fct_sales
    description: "Camada gold: fato de vendas com métricas básicas"
    columns:
      - name: total
        tests: [not_null]
