name: "moura_dbt"
version: "1.0.0"
config-version: 2

profile: "moura_profile"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  moura_dbt:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
